---
- name: Install Dependency packages
  package:
    name:
      - acl
      - sudo
      - python3-pexpect
      - libyaml-perl
      - libdbd-pg-perl
      - libdbi-perl
      - php
      - php-pgsql
      - php-imap
      - php-curl
      - php-cgi
      - php-xml
      - nginx
    state: present
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10

- name: Create temporary build directory for Davical
  ansible.builtin.tempfile:
    state: directory
  register: davical_temp_dir_raw

- name: Set Temporary Path
  ansible.builtin.set_fact:
    davical_temp_dir: "{{ davical_temp_dir_raw.path }}"
