---
- name: Make group for {{ davical_service_user }}
  ansible.builtin.group:
    name: "{{ davical_service_user }}"
    state: present
    system: true

- name: Make service user for {{ davical_service_user }}
  ansible.builtin.user:
    name: "{{ davical_service_user }}"
    state: present
    create_home: true
    groups: "{{ davical_service_user }}"
    system: true
    shell: /bin/bash
