---
- name: Create davical directory
  ansible.builtin.file:
    path: "{{ davical_dir }}"
    state: directory
    owner: "{{ davical_service_user }}"
    group: "{{ davical_service_user }}"
    mode: '700'

- name: Get Davical Zip
  ansible.builtin.get_url:
    url: "{{ davical_url }}"
    dest: "{{ davical_temp_dir }}/{{ davical_zip_filename }}"
    force: true
    owner: "{{ davical_service_user }}"
    group: "{{ davical_service_user }}"
    mode: "0700"
    validate_certs: "true"

- name: Unzip Davical
  ansible.builtin.unarchive:
    src: "{{ davical_temp_dir }}/{{ davical_zip_filename }}"
    dest: "{{ davical_dir }}"
    remote_src: true

- name: Get Davical AWL Zip
  ansible.builtin.get_url:
    url: "{{ davical_awl_url }}"
    dest: "{{ davical_temp_dir }}/{{ davical_awl_zip_filename }}"
    force: true
    owner: "{{ davical_service_user }}"
    group: "{{ davical_service_user }}"
    mode: "0700"
    validate_certs: "true"

- name: Unzip Davical
  ansible.builtin.unarchive:
    src: "{{ davical_temp_dir }}/{{ davical_awl_zip_filename }}"
    dest: "{{ davical_dir }}"
    remote_src: true
