---
- name: Edit davical file already deployed
  ansible.builtin.replace:
    path: "{{ davical_installed_config_file }}"
    regexp: "TEXT_TO_FIND"
    replace: "TEXT_TO_ADD"
    owner: "{{ davical_service_user }}"
    group: "{{ davical_service_user }}"
    mode: '0700'

- name: Deploy fresh app config file
  ansible.builtin.template:
    src: "{{ davical_deployed_config_file }}"
    dest: "{{ davical_dir }}/CONFIG_PATH"
    force: true
    mode: '0700'  # Ansible-Lint hates when this isn't set

- name: Own all of the davical folder
  ansible.builtin.file:
    path: "{{ davical_dir }}"
    state: directory
    recurse: true
    owner: '{{ davical_service_user }}'
    group: '{{ davical_service_user }}'
