---
- name: Template out davical Service
  ansible.builtin.template:
    src: davical.service.j2
    dest: "/etc/systemd/system/davical.service"
    force: true
    mode: '0644'  # Ansible-Lint hates when this isn't set

- name: Add overwrite_certs.sh
  ansible.builtin.template:
    src: overwrite_certs.sh.j2
    dest: "{{ davical_dir }}/overwrite_certs.sh"
    force: true
    mode: '0700'  # Ansible-Lint hates when this isn't set
    owner: "{{ davical_service_user }}"
    group: "{{ davical_service_user }}"

- name: Copy initial cert to appropriate directory
  ansible.builtin.copy:
    src: "{{ davical_inital_cert_location }}/{{ davical_external_domain }}.crt"
    dest: "{{ davical_certificate_path }}"
    remote_src: true
    force: true
    owner: "{{ davical_service_user }}"
    group: "{{ davical_service_user }}"
    mode: "0700"

- name: Copy initial key to appropriate directory
  ansible.builtin.copy:
    src: "{{ davical_inital_cert_location }}/{{ davical_external_domain }}.key"
    dest: "{{ davical_key_path }}"
    remote_src: true
    force: true
    owner: "{{ davical_service_user }}"
    group: "{{ davical_service_user }}"
    mode: "0700"

- name: Make override directory
  ansible.builtin.file:
    path: "{{ davical_cert_renewer_path }}"
    state: directory
    mode: '0755'

- name: Deploy davical override
  ansible.builtin.template:
    src: cert-renewer.davical.override.j2
    dest: "{{ cert_renewer_path }}/override.conf"
    force: true
    mode: '0770'  # Ansible-Lint hates when this isn't set

- name: Do post configuration activities for davical
  become_user: "{{ davical_service_user }}"
  ansible.builtin.command:
    cmd: "{{ davical_post_config_command }}"
    chdir: "{{ davical_dir }}"
  changed_when: false

- name: Ensure cert-renewer@bitwarden.timer is started
  ansible.builtin.service:
    name: "{{ davical_cert_timer }}"
    state: started
    enabled: true

- name: Ensure davical is restarted
  ansible.builtin.service:
    name: "{{ davical_name }}"
    state: restarted
    enabled: true
